trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: 'install_terraform'
  inputs:
    secureFile: 'terraform.zip'

- script: |
    unzip $(install_terraform.secureFilePath) -d $(Agent.ToolsDirectory)/terraform
    echo '##vso[task.prependpath]$(Agent.ToolsDirectory)/terraform'
  displayName: 'Install Terraform'

- script: |
    terraform init
    terraform validate
  displayName: 'Terraform Init & Validate'

- script: terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: terraform apply tfplan
  displayName: 'Terraform Apply'
